# typed: strict
# frozen_string_literal: true

# This file is generated by scripts/gen-homebrew-formula.sh on each olai-trestle
# release. Do not edit by hand — edits will be overwritten on the next release.
class Trestle < Formula
  desc "Unified CLI for proto-driven code generation and full-project scaffolding"
  homepage "https://github.com/open-lakehouse/trestle"
  license "Apache-2.0"
  # No explicit `version`: Homebrew scans it from the `olai-trestle-v<version>`
  # segment of the download URLs (an explicit line trips FormulaAudit/Version as
  # redundant).

  # No `livecheck` block on purpose: this is our own tap, and the
  # `bump-homebrew` CI job regenerates this formula on every olai-trestle release,
  # so there is nothing for Homebrew's autobump bot to discover. (A livecheck
  # here would also need a per-crate tag filter — other workspace crates tag
  # under different prefixes — which `url :stable` cannot express.)

  on_macos do
    on_arm do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.5/trestle-aarch64-apple-darwin.tar.gz"
      sha256 "f2f454618f338168b570e192dccd567bad2170e8d575ff70d04d98c507fbe84d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.5/trestle-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3d4e752c35a1b004f635de4dc5d2b37a423495c70c8b43032bc6ec5cef13acc9"
    end
    on_intel do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.5/trestle-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3ad969352663114b73ae0d105ee725bafe2e5cd90a3290770be75d55333c761f"
    end
  end

  # release-binaries.yml packages with `leading-dir: true`, so every archive
  # unpacks to a single `trestle-<target>/` directory containing the binary.
  # Homebrew does not strip that dir, so glob for the binary wherever it landed
  # rather than hard-coding the per-platform target triple.
  def install
    bin.install Dir["**/trestle"].first
  end

  test do
    assert_match "trestle", shell_output("#{bin}/trestle --version")
  end
end
