# typed: strict
# frozen_string_literal: true

# This file is generated by scripts/gen-homebrew-formula.sh on each olai-trestle
# release. Do not edit by hand — edits will be overwritten on the next release.
class Trestle < Formula
  desc "Unified CLI for proto-driven code generation and full-project scaffolding"
  homepage "https://github.com/open-lakehouse/trestle"
  license "Apache-2.0"
  # No explicit `version`: Homebrew scans it from the `olai-trestle-v<version>`
  # segment of the download URLs (an explicit line trips FormulaAudit/Version as
  # redundant).

  # No `livecheck` block on purpose: this is our own tap, and the
  # `bump-homebrew` CI job regenerates this formula on every olai-trestle release,
  # so there is nothing for Homebrew's autobump bot to discover. (A livecheck
  # here would also need a per-crate tag filter — other workspace crates tag
  # under different prefixes — which `url :stable` cannot express.)

  on_macos do
    on_arm do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.7/trestle-aarch64-apple-darwin.tar.gz"
      sha256 "918d9f9f88d6c3cce0515c584ddb91d4a09b676452bff39b4d985406a75fd8d2"
    end
    on_intel do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.7/trestle-x86_64-apple-darwin.tar.gz"
      sha256 "c6ed30ef469f973b21ba24b1d14170cef74ded22e82ece02f76cad27fcfe1db7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.7/trestle-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a0b484e99c09de455dd39ee207be207c98832ba2c6cad5d1542ce4e5cb239665"
    end
    on_intel do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.7/trestle-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0a4445bd262b313a0ad8000d269a3a148651d3f69588864d298ea1f8b5b514c9"
    end
  end

  # release-binaries.yml packages with `leading-dir: true`, so every archive
  # unpacks to a single `trestle-<target>/` directory containing the binary.
  # Homebrew does not strip that dir, so glob for the binary wherever it landed
  # rather than hard-coding the per-platform target triple.
  def install
    bin.install Dir["**/trestle"].first
  end

  test do
    assert_match "trestle", shell_output("#{bin}/trestle --version")
  end
end
