# typed: strict
# frozen_string_literal: true

# This file is generated by scripts/gen-homebrew-formula.sh on each olai-trestle
# release. Do not edit by hand — edits will be overwritten on the next release.
class Trestle < Formula
  desc "Unified CLI for proto-driven code generation and full-project scaffolding"
  homepage "https://github.com/open-lakehouse/trestle"
  license "Apache-2.0"
  # No explicit `version`: Homebrew scans it from the `olai-trestle-v<version>`
  # segment of the download URLs (an explicit line trips FormulaAudit/Version as
  # redundant).

  # No `livecheck` block on purpose: this is our own tap, and the
  # `bump-homebrew` CI job regenerates this formula on every olai-trestle release,
  # so there is nothing for Homebrew's autobump bot to discover. (A livecheck
  # here would also need a per-crate tag filter — other workspace crates tag
  # under different prefixes — which `url :stable` cannot express.)

  on_macos do
    on_arm do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.6/trestle-aarch64-apple-darwin.tar.gz"
      sha256 "1042cb8300d7d44f4a8f4775b20f9a9c60e33afd0f9a3b68f8d65ab6db28ce0c"
    end
    on_intel do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.6/trestle-x86_64-apple-darwin.tar.gz"
      sha256 "c89a5b083a959f39203d1308f9d9b9049ecc052e20c64413ad1af55d06db7ab8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.6/trestle-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8bde14c0e904278ff4d9ccdb2ab6f1e6e16605cfa1a564da7e119a145ef2c46a"
    end
    on_intel do
      url "https://github.com/open-lakehouse/trestle/releases/download/olai-trestle-v0.0.6/trestle-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "05f8be32c01325d93b7fd0093c93d94e73f087af555d0b7e599787bea62806f7"
    end
  end

  # release-binaries.yml packages with `leading-dir: true`, so every archive
  # unpacks to a single `trestle-<target>/` directory containing the binary.
  # Homebrew does not strip that dir, so glob for the binary wherever it landed
  # rather than hard-coding the per-platform target triple.
  def install
    bin.install Dir["**/trestle"].first
  end

  test do
    assert_match "trestle", shell_output("#{bin}/trestle --version")
  end
end
